### ISSUE TITLE
DietPi support

### ISSUE THREAD

**Issue by ghctim** [estruyf/unicorn-busy-server#8]
i had the script working fine on DietPi then I did a pull to the latest Repo and I can't get it to reinstall. I get an unsupported distro error

**Comment by ghctim** [comment]
root@DietPi:~# curl -LSs https://raw.githubusercontent.com/estruyf/unicorn-busy-server/master/install.sh | sudo bash -
The requried files are missing... lets clone everything from git...
Cloning files from git using HTTPS to /root/unicorn-busy-server...
bash: line 120: lsb_release: command not found
Unsupported distribution, please consider submitting a pull request to extend the script

**Comment by ghctim** [comment]
if i try to start server.py manually
root@DietPi:~/unicorn-busy-server# ./start.sh 
Traceback (most recent call last):
  File "./server.py", line 12, in <module>
    from lib.unicorn_wrapper import UnicornWrapper
  File "/root/unicorn-busy-server/lib/unicorn_wrapper.py", line 5, in <module>
    import spidev
ModuleNotFoundError: No module named 'spidev'

**Comment by ghctim** [comment]
had to run a apt-get install -y python3-spidev.
New error
Traceback (most recent call last):
  File "./server.py", line 12, in <module>
    from lib.unicorn_wrapper import UnicornWrapper
  File "/root/unicorn-busy-server/lib/unicorn_wrapper.py", line 7, in <module>
    from unicornhatmini import UnicornHATMini
ModuleNotFoundError: No module named 'unicornhatmini'

**Comment by ghctim** [comment]
installed this next - https://github.com/pimoroni/unicornhatmini-python

**Comment by ghctim** [comment]
still getting Traceback (most recent call last):
  File "./server.py", line 12, in <module>
    from lib.unicorn_wrapper import UnicornWrapper
  File "/root/unicorn-busy-server/lib/unicorn_wrapper.py", line 7, in <module>
    from unicornhatmini import UnicornHATMini
ModuleNotFoundError: No module named 'unicornhatmini'

**Comment by ghctim** [comment]
i manually installed gpizero but i still can't get it running

**Comment by ghctim** [comment]
i give up for now! PLease advise as I am using the distro and guide from https://www.eliostruyf.com/diy-building-busy-light-show-microsoft-teams-presence/

**Comment by ghctim** [comment]
fixed it by manually installed the pre-requesites but looks like one of your commands to check versions isn't supported by dietpi

**Comment by ghctim** [comment]
Dietpie doesn't appear to support the lsb_release -si

**Comment by estruyf** [comment]
@ghctim thanks for the feedback. @j-maynard updated the installation scripts, and `DietPi` seems to not yet supported. 

Just in case, I have added the old installation script as a fallback: https://github.com/estruyf/unicorn-busy-server/blob/master/install-fallback.sh

Feel free to try it out.

**Comment by spazool** [comment]
Hi Elio,

I am building the busy light project (my first project), and after running the "install-fallback.sh" script, i get the following errors:

Setting up python3-dev (3.7.3-1) ...
Processing triggers for libc-bin (2.28-10+rpi1) ...
Could not open requirements file: [Errno 2] No such file or directory: './requirements.txt'
cp: cannot stat 'busylight.service': No such file or directory
Failed to enable unit: Unit file busylight.service does not exist.
Failed to start busylight.service: Unit busylight.service not found.
chmod: cannot access './start.sh': No such file or directory

I am running a Pi Zero W with DietPi v6.31.2

Is there something I am missing?

**Comment by estruyf** [comment]
@spazool what does the service show if you run: `systemctl status busylight`? You should normally see if it's running or failed.

What you can also try is to run the server with the following command: `python3 server.py`. Check if this works.

**Comment by ydogandjiev** [comment]
Thanks for putting this great project together @estruyf! There are a few additional issues with DietPi that I ran into beyond what's discussed on this thread:
1. The default user is dietpi instead of pi so the working directory for the busylight.service file needs to be updated to something like:
`/home/dietpi/unicorn-busy-server`
2. Additionally, the install-fallback.sh script sets permissions on the wrong file. The service is trying to run `python3 server.py` and not `sh start.sh` so I had to set execution permissions on the server.py file itself:
`sudo chmod +x ./server.py`

I also ran into a bunch of issues getting the Unicorn pHat but I will delve into that some other time. I have also opened an issue about that here (to track the software problems I ran into):
https://github.com/pimoroni/unicorn-hat/issues/141
